### ISSUE TITLE
[BUG] Prespeed on hud displays incorrect value

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/SurfTimer#126]
**Describe the bug**
When prespeed is set to 350, it will display as 351 on center hud and middle center hud.

**Expected behavior**
Display 350

**Screenshots**
![prespeed 351](https://user-images.githubusercontent.com/63484108/81991496-36aca900-95f6-11ea-89ab-bd78b49f1442.PNG)

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
dev 285.7

**Additional context**
Bug did not appear in 285

**Comment by Kyli3Boi** [comment]
I can confirm, also happening to me on my test server with 285.7

**Comment by Kyli3Boi** [comment]
Have tested on my test server with 285.95 bug is there too

**Comment by qawery-just-sad** [comment]
1. @olokos yes this is still in 1.0.1
2. it's probably displaying correct value (just use `cl_showpos 1` and look at vel)
3. it's either the way of rounding number that changed or speed limiter issue

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment]
I am still able to reproduce this. 

**More info** This happens only when turning. If moving in a straight line it displays as 350 so its somehow getting the 1 speed from the turn.

![image](https://user-images.githubusercontent.com/64275139/94996081-bbe32b00-05a2-11eb-8a5c-e30fcd1f1b6d.png)

**Comment by Bara** [comment]
We could use [RoundToFloor](https://sourcemod.dev/#/float/function.RoundToFloor) here. I think sourcemod is probably too slow here to handle this correctly.

**Comment by Bara** [comment]
or just we print the float value as `%.0f` should do the same, without rounding.

**Comment by Kyli3Boi** [comment]
%.0f still shows 351 when jumping in a circle but it shows 249 when moving in a straight line

**Comment by Kyli3Boi** [comment]
RoundToFloor still shows 351 when jumping in a circle but now most of the time it shows 250 when moving in a straight line (sometimes 249)

**Comment by Kyli3Boi** [comment]
RoundFloat gives a consistent 250 speed in straight line but still shows 351 when jumping in circle

**Comment by Kyli3Boi** [comment]
Setting a decimal point explains why this is happening a bit better.

When moving in a straight line sometimes the speed is 250u/s and sometimes its 249.9u/s

When jumping in a circle its a constant 351.1u/s which is why rounding down still displays 351u/s

**Comment by dPexxIAM** [comment]
unable to reproduce https://github.com/surftimer/SurfTimer/commit/6c4b3226b3d84ebaeb86fba94b2e7c54b763e643
