### ISSUE TITLE
[BUG] Some chat outputs spamming console

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/SurfTimer#127]
**Describe the bug**
There are some outputs by surftimer that are spammed up to 12 times in the chat. Happens when i try to initiate a vote extend during a map vote.

**Expected behavior**
Only print to chat one time.

**Screenshots**
![repeating chat text](https://user-images.githubusercontent.com/63484108/82038191-04339800-9658-11ea-9e27-5571205ad44c.PNG)

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
dev 285.7

**Additional context**
Bug was not in 285

**Comment by FR33K1LL** [comment]
Update:
Happens anytime i vote extend, not just during a map vote.

**Comment by Kyli3Boi** [comment]
Same issue using 285.5

**Comment by FR33K1LL** [comment]
ive noticed !colors also does this on 285.95

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by dPexxIAM** [comment]
guess not ^
