### ISSUE TITLE
[BUG] Speed limiting not working as intended when not jumping out of zone

### ISSUE THREAD

**Issue by samatazz** [surftimer/SurfTimer#132]
**Describe the bug**
If you just run off a platform and dont jump the next time you reset dosn't limit your speed.
e.g surf_utopia_njv just run off the platform without jumping then fail while holding space and you will be launched.

**Expected behaviour**
Should limit your speed when leaving the start zone/entering it.

**Screenshots**
N/A

**Plugin List**
N/a
**Timer Version**
285.95. Compiled today.

**Additional context**
ive tried ck_one_jump_limit "0" and ck_one_jump_limit "1" neither of them effect the issue at all.

**Comment by erikjunker** [comment]
I'm also having this issue. It's breaking a lot of maps now that the players have discovered this bug. Hope it'll get fixed asap.

**Comment by sneak-it** [comment]
Is this similar to #42 ?

**Comment by samatazz** [comment]
No. That one can be fixed by changing the one jump limit. That one is also when you leave and come back you can exceed it with pre hops this one allows telehops.

**Comment by erikjunker** [comment]
Here's a video showcasing the issue @sneak-it
https://www.youtube.com/watch?v=5OZPho4XVvc

**Comment by qawery-just-sad** [comment]
do you have RNGfix plugin?
if yes try the map without it
(for some reason i feel that's the issue)

**Comment by erikjunker** [comment]
Yes, I do use the RNGfix plugin, however it's not the culprit. I just tried disabling it and was able to replicate the issue still

**Comment by Kyli3Boi** [comment]
You can fix this by changing the position of the start zone.

Issue above occurs 
![image](https://user-images.githubusercontent.com/64275139/82048626-47702400-96b5-11ea-8af4-52699958d707.png)

When changed to this then issue is no longer present
![image](https://user-images.githubusercontent.com/64275139/82048715-68d11000-96b5-11ea-8c4f-65ecf3cc7d63.png)

I think it has something to do with the restart point being inside the start zone

**Comment by erikjunker** [comment]
Confirmed that the problem can be solved with @Kyli3Boi's suggestion above.. It will have to do for now.

**Comment by qawery-just-sad** [comment]
@sneak-it (or someone that knows this code better than me) is there something in code that tries to check for boost in start zone and allows for the boost inside it?

**Comment by dPexxIAM** [comment]
If you could try recompiling your timer with these lines added https://github.com/fluffyst/Surftimer/blob/563f4f749b7d29fd9d0308fd6352029300414e6e/addons/sourcemod/scripting/surftimer/hooks.sp#L1282

and let me know if the issue persists, would be grand!

**Comment by Kyli3Boi** [comment]
@dPexxIAM Tested and does not work

**Comment by dPexxIAM** [comment]
Which ck_limit_speed_type are you using?

**Comment by Kyli3Boi** [comment]
New style "1"

**Comment by Kyli3Boi** [comment]
Also i dont know if it was doing this before but what i can see is that is that you can only do this once. 
EG. Run off start, hit ground, boost but if you then try hit ground again it locks you in the start zone

**Comment by dPexxIAM** [comment]
Seems like there is a bunch of stuff missing in this fork which should have been added previously...

https://github.com/fluffyst/Surftimer/commit/562c53cee3b179e28fcb4b97db2afd461d040473
https://github.com/fluffyst/Surftimer/commit/562c53cee3b179e28fcb4b97db2afd461d040473
https://github.com/fluffyst/Surftimer/commit/4eddd22e8fa88207304ba7e22afaeb2c741d680e

I don't have time to merge this stuff myself at the minute. The missing code is more than likely the cause of this issue.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by dPexxIAM** [comment]
@samatazz i can't repro, re-open if need be
