### ISSUE TITLE
[BUG] Timer cannot start after getting a bonus SR

### ISSUE THREAD

**Issue by erikjunker** [surftimer/SurfTimer#145]
**Describe the bug**
The timer cannot start after beating the bonus SR and going directly to the start zone again - e.g. with !r or !b 1 (this might also apply to the map record, not tested).
I was not able to replicate the issue when I beat the bonus record and jumped back out of the end zone to hit one of the tp triggers - then the timer was still able to start just fine.

**Expected behavior**
The timer should be able to start after beating the bonus record.

**Timer Version**
Latest dev branch

**Additional context**
Killing yourself, switching teams, going from spec to player again doesn't reset the timer. Only way to fix the timer I could find was to rejoin the server.

Will need to do more testing on this one.... I was able to replicate the issue on surf_summit, but couldn't replicate the issue on surf_escape_final

**Comment by Kyli3Boi** [comment]
Is this when you walk through the teleports to go to bonuses?

If you use !bonus the reset to start shouldn't happen, attest that's how it works for me

**Comment by bctse** [comment]
Can confirm, im experiencing the same issue. Once a person beats a bonus record, their timer will not start i they try to do the regular map.

**Comment by Kyli3Boi** [comment]
I also have same issue. Have to quit and rejoin server. Latest Dev

**Comment by stunslave** [comment]
Also been getting this issue a lot recently. (latest dev)

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by dPexxIAM** [comment]
can't seem to reproduce, @erikjunker re-open if needed
