### ISSUE TITLE
[Suggestion] Center Speed Display Colors

### ISSUE THREAD

**Issue by stunslave** [surftimer/SurfTimer#193]
**Describe the solution you'd like**
If possible a way to change the colors of the Center Speed Display or for the Center Speed Display to change colors automatically if speed is gained or lost while surfing. (Green = Speed gained / Red = Speed lost or something)

**Additional context**
![image](https://user-images.githubusercontent.com/47533535/85861139-245e8700-b7c0-11ea-8ef8-ac4f13330bbb.png)

**Comment by qawery-just-sad** [comment]
it's right there called "speed gradient" and pick "[momentum]" option

**Comment by stunslave** [comment]
That changes the Center Hud Speed colors and not the Center Speed Display colors. 
I added a image for you.
![image](https://user-images.githubusercontent.com/47533535/85864630-12331780-b7c5-11ea-839b-adf64de58081.png)

**Comment by qawery-just-sad** [comment]
nope it does center hud for me

**Comment by qawery-just-sad** [comment]
https://youtu.be/mvWIBMWOgZQ

**Comment by stunslave** [comment]
Na it stays completely white no matter what I change it to.

**Comment by qawery-just-sad** [comment]
mistakes were made

**Comment by shipyy** [comment]
i believe this could be closed (#423 & #427)

**Comment by dPexxIAM** [comment]
closed as per https://github.com/surftimer/SurfTimer/issues/193#issuecomment-1206019352
