### ISSUE TITLE
[Suggestion] VIP Spam Protection Ignore.

### ISSUE THREAD

**Issue by stunslave** [surftimer/SurfTimer#195]
**Describe the solution you'd like**
If possible a cvar for VIP to ignore the ck_chat_spamprotection_time 

//if enabled, VIPs will ignore the spam protection time.
**ck_spamignore_vip (or something)**

**Additional context**
Basically to allows VIP's to over use or spam commands like sm_back or practice mode without being kicked for spamming. Without disabling spam protection.

**Comment by sneak-it** [comment]
Have your players use the actual command binds instead of chat binds.

How they have it:
`bind key "say !back"`
How it should be:
`bind key sm_back`

Totally valid feature request though, so I'll keep it up here.

**Comment by Kyli3Boi** [comment]
Is this still a thing? iv been testing it with !say back and it never kicks me just says in chat "You are flooding the server"?

This is with me having VIP but no Admin

**Comment by dPexxIAM** [comment]
As sneak said above, your client's issues are that they are using chat binds rather than binding the command itself.

I see absolutely zero reasons to consider this.
