### ISSUE TITLE
[Suggestion] Remove IsPlayerVIP stock, standardize commands permissions

### ISSUE THREAD

**Issue by sneak-it** [surftimer/SurfTimer#217]
**Is your feature request related to a problem? Please describe.**
There are several commands which cannot be utilized with SourceMod's override system. There are internal checks inside these commands which make it not possible.

**Describe the solution you'd like**
Nuke the IsPlayerVIP stock and fix the shoddy commands.

**Describe alternatives you've considered**

**Additional context**

**Comment by sneak-it** [comment]
See #216 for one example

**Comment by dPexxIAM** [comment]
https://github.com/surftimer/SurfTimer/pull/439
