### ISSUE TITLE
[BUG] Double sound on timer start #249 in a different form

### ISSUE THREAD

**Issue by Kyli3Boi** [surftimer/SurfTimer#261]
**Describe the bug**
When there is no records set on the server then all is well but as soon as set a time and then change style the double sound bug is back.

**Expected behavior**
No double sound bug

**Screenshots**
https://youtu.be/zCDggh_S9qM

**Plugin List**
Latest Dev <code>"SurfTimer" (1.1.0-dev)</code>

**Additional context**
N/A

**Comment by dPexxIAM** [comment]
not able to reproduce with current code
