### ISSUE TITLE
[BUG] DELAYED POINTS / sometimes it doesn't give points

### ISSUE THREAD

**Issue by lordbarzbug** [surftimer/SurfTimer#268]
**Describe the bug**
**Im using SurfTimer 1.0.2 dev.** 
players cannot score points when they finish the map while sliding in normal mode.
but interestingly, they can get points in bonus and style modes without any problem.
And sometimes,
It doesn't give points when someone breaks his first personal record. After trying again, he finishes with a result worse than his personal record, giving him the score of his first record with a delay.

**Expected behavior**
How can we solve this problem?

**Screenshots**
[https://imgur.com/a/PYQ4E4W](https://imgur.com/a/PYQ4E4W)

**As you can see it looks like 9999/11. This problem is fixed when we retry to the console.**
When we finish the map in the bottom left chat, it says "Your data could not be verified please contact an administrator".

**Plugin List**
N/A

**Additional context**
N/A

**Comment by olokos** [comment]
```
L 11/25/2020 - 00:39:25: [CSCenterAnaEklentisi.smx] [DEBUG][CS.Center Ana Eklentisi] WeaponDrop event
L 11/25/2020 - 00:39:50: [SM] Exception reported: Client 11 is not in game
L 11/25/2020 - 00:39:50: [SM] Blaming: SurfTimer.smx
L 11/25/2020 - 00:39:50: [SM] Call stack trace:
L 11/25/2020 - 00:39:50: [SM]   [0] PrintToChat
L 11/25/2020 - 00:39:50: [SM]   [1] Line 43, C:\Users\oloko\Documents\GitHub\Surftimer-BUILD\include\colorlib.inc::CPrintToChat
L 11/25/2020 - 00:39:50: [SM]   [2] Line 4305, surftimer/misc.sp::StyleFinishedMsgs
L 11/25/2020 - 00:39:50: [SM]   [3] Line 7098, surftimer/sql.sp::SQL_UpdateStyleRecordCallback2
```

That's the stack trace you dm'd me, I'll leave it here so it's not going to be missed, as it's crucial to fixing the bugs, thanks for the report!

**Comment by dPexxIAM** [comment]
old dev branch bug, not able to reproduce
