### ISSUE TITLE
[BUG] Teleporting Between Stages Causes Timer to Start

### ISSUE THREAD

**Issue by CustomStats** [surftimer/SurfTimer#333]
**Describe the bug**
When the `!stage` command is utilized to go from one stage to another, the player's timer will instantly start.

**Expected behavior**
The timer should not start for this new stage until the person leaves the zone.

**Screenshots**
https://streamable.com/m97tsg

**Plugin List**
Most up-to-date master version

**Comment by DaLLuZZ** [comment]
because `g_bWrcpTimeractivated[client]` should be set to false

**Comment by CustomStats** [comment]
No, the zones are not flat. It's replicated no matter the map as well. If you go out of the stage zone and then back in, the time will be set to 0 like it should be. Here's a video of that and to show that the zoning is "right" https://streamable.com/95e0it

**Comment by dPexxIAM** [comment]
> No, the zones are not flat. It's replicated no matter the map as well. If you go out of the stage zone and then back in, the time will be set to 0 like it should be. Here's a video of that and to show that the zoning is "right" https://streamable.com/95e0it

is it reproducible with the latest release? https://github.com/surftimer/Surftimer-Official/releases/tag/1.0.2

**Comment by dPexxIAM** [comment]
trying chucking g_bWrcpTimeractivated[client] = false;

above this line here: https://github.com/surftimer/Surftimer-Official/blob/605182b84c41edd1f7f6a2b3851419742e362213/addons/sourcemod/scripting/surftimer/commands.sp#L1294

**Comment by CustomStats** [comment]
Fixed with https://github.com/surftimer/Surftimer-Official/commit/b785e3ca56b44ab026adfc775f6557f7c5376f05
