### ISSUE TITLE
[BUG] ck_prestige_rank_vip does not work

### ISSUE THREAD

**Issue by timyc** [surftimer/SurfTimer#35]
**Describe the bug**
ck_prestige_rank_vip will not work because the query to set the player's VIP boolean value is not executed in time (if at all), and the player is kicked beforehand.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment]
Am able to reproduce

<code>"SurfTimer" (1.1.0-dev)</code>

**Comment by tslashd** [comment]
Unable to reproduce.
