### ISSUE TITLE
[BUG] Recalculation

### ISSUE THREAD

**Issue by GimoDDak** [surftimer/SurfTimer#404]
**Describe the bug**
The problem is that some players' nicknames are displayed as "???" when recalculation is executed through the admin menu.
The nicknames of these players are UTF-8 characters.

**Expected behavior**
It should be output as a real nickname, not a "???".

**Screenshots**
![surf_panono0000](https://user-images.githubusercontent.com/100826395/156507910-6a51c5f4-e45e-4807-bce8-56a15a4e03f4.png)

**Plugin List**
https://github.com/surftimer/Surftimer-Official/releases/tag/1.1.0

**Additional context**
None

**Comment by sneak-it** [comment]
Please provide the output of `sm plugins list` executed from the server console.

Do you have an example of what one of these names *should* be?

**Comment by DaLLuZZ** [comment]
What do these lines do?
https://github.com/surftimer/Surftimer-Official/blob/7bb680edbc63818307839998fdcf5c29332ffe5e/addons/sourcemod/scripting/surftimer/sql.sp#L641-L644

**Comment by GimoDDak** [comment]
[SM] Listing 59 plugins:
  01 "Admin File Reader" (1.10.0.6510) by AlliedModders LLC
  02 "Admin Help" (1.10.0.6510) by AlliedModders LLC
  03 "Admin Menu" (1.10.0.6510) by AlliedModders LLC
  04 "Always Weapon Skins" (2.2.8) by Neuro Toxin
  05 "Anti-Flood" (1.10.0.6510) by AlliedModders LLC
  06 "Basic Chat" (1.10.0.6510) by AlliedModders LLC
  07 "Basic Comm Control" (1.10.0.6510) by AlliedModders LLC
  08 "Basic Commands" (1.10.0.6510) by AlliedModders LLC
  09 "Basic Info Triggers" (1.10.0.6510) by AlliedModders LLC
  10 "Basic Votes" (1.10.0.6510) by AlliedModders LLC
  11 "Bot fix for Surftimer" (1.0) by Busted
  12 "Client Preferences" (1.10.0.6510) by AlliedModders LLC
  13 "crouchboostfix" (2.0.0) by https://github.com/t5mat
  14 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  15 "TPFix" (1.0.2) by rio
  16 "Demo Record Fix" (1.0) by zer0.k
  17 "Discord API" (0.1.103) by Deathknife
  18 "Discord Utilities" (2.8-BETA) by Cruze
  19 "EndTouch Fix" (1.0) by rumour, mev
  20 "Fix Mapchange Crash" (1.2) by Ilusion9
  21 "SM Franug Country Flag Icons" (1.4) by Franc1sco franug
  22 "Fun Commands" (1.10.0.6510) by AlliedModders LLC
  23 "Fun Votes" (1.10.0.6510) by AlliedModders LLC
  24 "Gloves" (1.0.5) by kgns | oyunhost.net
  25 "goAFK Manager" (2.0.0) by SUPER TIMOR/ credits: Dr.Api
  26 "SurfTimer MapChooser" (1.8.3) by AlliedModders LLC & SurfTimer Contributors
  27 "mapchooser_maplister.smx"
  28 "Map Music Control with Dynamic Volume Control" (1.DZ.12_win) by DarkerZ[RUS]
  29 "Momentum surf fix '2" (1.1.4) by GAMMA CASE
  30 "Auto NAV file creator" (1.0) by shavit
  31 "Nextmap" (1.10.0.6510) by AlliedModders LLC
  32 "NightVision" (1.0.1) by GAMMA CASE
  33 "SurfTimer Nominations" (1.8.3) by AlliedModders LLC & SurfTimer Contributors
  34 "Player Commands" (1.10.0.6510) by AlliedModders LLC
  35 "PointServerCommandFilter" (1.0) by BotoX
  36 "PushFix - Definitive Edition" (1.0.0) by Original idea xutaxkamay | Implementation GAMMACASE
  37 "Remove Hint Dollar" (1.0) by MaZa
  38 "Reserved Slots" (1.10.0.6510) by AlliedModders LLC
  39 "RNGFix" (1.1.2) by rio
  40 "SurfTimer Rock The Vote" (1.8.3) by AlliedModders LLC & SurfTimer Contributors
  41 "Normalized Run Speed" (0.6) by sneaK
  42 "SaveChat" (SaveChat_1.2.1) by citkabuto
  43 "SourceBans++: Admin Config Loader" (1.6.4) by AlliedModders LLC, SourceBans++ Dev Team
  44 "SourceBans++: Bans Checker" (1.6.4) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  45 "SourceBans++: SourceComms" (1.6.4) by Alex, SourceBans++ Dev Team
  46 "SourceBans++: Main Plugin" (1.6.4) by SourceBans Development Team, SourceBans++ Dev Team
  47 "SourceBans++ Report Plugin" (1.6.4) by RumbleFrog, SourceBans++ Dev Team
  48 "SourceBans++: SourceSleuth" (1.6.4) by ecca, SourceBans++ Dev Team
  49 "ServerAdvertisements3" (3.1.4) by ESK0
  50 "[BASH] (Blacky's Anti-Strafehack)" (2.0) by Blacky, edited by carnifex
  51 "Sound Commands" (1.10.0.6510) by AlliedModders LLC
  52 "SurfTimer-Discord" (2.1.1) by Sarrus
  54 "SurfTimer" (1.0.dev) by All contributors
  55 "sv_airaccelerate.smx"
  56 "S-Downloader" (1.1.2.22 - Dev) by Starbish
  58 "SurfTimer Vote Extend" (1.8.3) by SurfTimer Contributors
  59 "Weapons & Knives" (1.7.5) by kgns | oyunhost.net

After recalculation, Korean and Japanese nicknames are displayed as "????"
like **최강선하** (before) -> **????** (after recalculation)

**Comment by dPexxIAM** [comment]
Which collation are your database tables using? Change them to utf8mb4_general_ci, should fix the issue i think.

**Comment by GimoDDak** [comment]
I've had this problem for a long time. Not sure if it's a bug, so I haven't opened an issue on github until now
![1](https://user-images.githubusercontent.com/100826395/156889492-2a22e118-de83-42cd-a6d8-1d4124473c61.PNG)
It is already set. I don't know why, but at some point it's changed to a real nickname

**Comment by dPexxIAM** [comment]
this was using old dev branch, and i'm not able to reproduce with current code.
