### ISSUE TITLE
[BUG] Inconsistent rank for records with same runtime between calculations

### ISSUE THREAD

**Issue by coverrt** [surftimer/SurfTimer#408]
**Describe the bug**
When calculating player rankings at each scope (checkpoint, bonus, map), if two or more rows have the same runtime the order of those rows is unguaranteed from the database.

First calculation

```diff
  | Player | Runtime | Rank |
  | :----: | ------- | :--: |
  |  1234  | 6.85547 |  1   |
  |  2345  | 6.85547 |  2   |
+ |  3456  | 6.85547 |  3   |
  |  4567  | 6.86719 |  4   |
  |  5678  | 6.87891 |  5   |
```

Future calculation

```diff
  | Player | Runtime | Rank |
  | :----: | ------- | :--: |
+ |  3456  | 6.85547 |  1   |
  |  1234  | 6.85547 |  2   |
  |  2345  | 6.85547 |  3   |
  |  4567  | 6.86719 |  4   |
  |  5678  | 6.87891 |  5   |
```

**Expected behavior**
Consistent rank and points for two or more records with the same runtime when calculated.

**Additional context**
A solution could be assigning the same rank to each row with the same runtime. This allows players to have consistent ranks and points regardless of the database returning the rows in an unguaranteed order.

| Player | Runtime | Rank |
| :----: | ------- | :--: |
|  1234  | 6.85547 |  1   |
|  3456  | 6.85547 |  1   |
|  2345  | 6.85547 |  1   |
|  4567  | 6.86719 |  2   |
|  5678  | 6.87891 |  3   |

| Player | Runtime | Rank |
| :----: | ------- | :--: |
|  2345  | 6.85547 |  1   |
|  3456  | 6.85547 |  1   |
|  1234  | 6.85547 |  1   |
|  4567  | 6.86719 |  2   |
|  5678  | 6.87891 |  3   |

**Comment by dPexxIAM** [comment]
Seems fine, although we should avoid using Rank as a column name as it's used a reserved word in mySQL 8.0.2+

**Comment by coverrt** [comment]
Can you clarify what seems fine?

**Comment by dPexxIAM** [comment]
will be fixed with upcoming release https://github.com/surftimer/SurfTimer/pull/459
