### ISSUE TITLE
[BUG] Player Skillgroups

### ISSUE THREAD

**Issue by tslashd** [surftimer/SurfTimer#450]
**Describe the bug**
```
L 06/20/2022 - 00:06:24: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 06/20/2022 - 00:06:24: [SM] Blaming: SurfTimer.smx
L 06/20/2022 - 00:06:24: [SM] Call stack trace:
L 06/20/2022 - 00:06:24: [SM]   [0] GetArraySize
L 06/20/2022 - 00:06:24: [SM]   [1] Line 2508, c:\Users\t\Documents\addons\sourcemod\scripting\surftimer/misc.sp::GetSkillgroupIndex
L 06/20/2022 - 00:06:24: [SM]   [2] Line 1912, c:\Users\t\Documents\addons\sourcemod\scripting\surftimer/sql.sp::sql_selectPlayerProfileCallback
```

Not sure what causes this error, nor what happens in the server when it gets thrown. 
Skillgroups file has not changed in ages on my servers so I doubt it's the config bugging it out.

`misc.sp`
![image](https://user-images.githubusercontent.com/74899888/174538741-866bb190-6816-4e4a-985d-49553151bb17.png)

`sql.sp`
![image](https://user-images.githubusercontent.com/74899888/174538694-13061383-9184-4949-b24f-4904b870764d.png)

**Comment by 1zc** [comment]
@tslashd Hey, could you upload your `skillgroups.cfg`? I can't seem to replicate this

**Comment by tslashd** [comment]
@1zc converted to `TXT` for obvious reasons (cba to do pastebin 😆) [skillgroups.txt](https://github.com/surftimer/SurfTimer/files/9016941/skillgroups.txt)

**Comment by tslashd** [comment]
Have not seen this happen after I changed some `ID`'s for the ranks in _skillgroups.cfg_

The fix was the very first _skillgroup_ needs to start with `1`, instead of `0` how I had it.

Closing the issue.
