### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kalifokendion** [surftimer/SurfTimer#478]
**Describe the bug**
Lots of lag 

[SM] Exception reported: Invalid memory access
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [1] Line 412, /home/runner/work/SurfTimer/SurfTimer/addons/sourcemod/scripting/include/colorlib.inc::CRemoveTags
[SM]   [2] Line 5335, surftimer/misc.sp::RemoveColors
[SM]   [3] Line 384, surftimer/timer.sp::SetClanTag

**Comment by Kalifokendion** [comment]
The server has access, all tags are working. 
Default_titles are disabled. 
Customtitles also work.

**Comment by stunslave** [comment]
This issue is fixed, updating sourcemod fixed it.. (No idea why)
