### ISSUE TITLE
[BUG] Country tag does not show for "default" titles.

### ISSUE THREAD

**Issue by ramadan8** [surftimer/SurfTimer#479]
**Describe the bug**
The country tag that would normally show before other roles does not show for default titles, such as those for VIPs or admins. I'm not sure if this is intended behaviour but I'd like to know if there is some way I can change this.

The strange thing I've found is that if `ck_admin_country_tags` is set to `0` it displays a country tag but it is wrong, saying US instead of ZA.

**Expected behavior**
I'd expect for my name to start with `ZA | [WOLF]`.

**Screenshots**
`ck_admin_country_tags 0`

![](https://i.imgur.com/eqnRlBa.png)

`ck_admin_country_tags 1`

![](https://i.imgur.com/2Q6C39j.png)

**Plugin List**
Nothing that should affect this issue, but here:

```
admin-flatfile.smx
adminhelp.smx
adminmenu.smx
antiflood.smx
basebans.smx
basechat.smx
basecomm.smx
basecommands.smx
basetriggers.smx
basevotes.smx
clientprefs.smx
crouchboostfix.smx
csgo_movement_unlocker.smx
EndTouchFix.smx
funcommands.smx
funvotes.smx
headbugfix.smx
momsurffix2.smx
nextmap.smx
playercommands.smx
pushfix_de.smx
randomcycle.smx
reservedslots.smx
rngfix.smx
rockthevote.smx
runspeed.smx
sounds.smx
st-mapchooser.smx
st-nominations.smx
st-rockthevote.smx
st-voteextend.smx
SurfTimer-telefinder.smx
SurfTimer.smx
```

**Comment by dPexxIAM** [comment]
This is due to your GeoIP database being out of date and is unrelated to SurfTimer.

https://mailfud.org/geoip-legacy/

**Comment by ramadan8** [comment]
The issue is not so much with the country code that is shown, but with the fact that no country code is shown at all in the scoreboard. I'm wondering how I could fix that, as I'm using `ck_admin_country_tags "1"` on my server and it does not show up, which seems antithetical to the documentation:

```
g_iAdminCountryTags = AutoExecConfig_CreateConVar("ck_admin_country_tags", "0", "(1 / 0) Enable/Disable country tags for admins", _, true, 0.0, true, 1.0);
```

Or am I misunderstanding this cvar?
