### ISSUE TITLE
[Suggestion] Additional query optimization for #502

### ISSUE THREAD

**Issue by coverrt** [surftimer/SurfTimer#506]
Please test to ensure the current and proposed statements have consistent results.

---

## db_selectTotalStageCount

The query plan for this statement may use temporary and filesort extras.

https://github.com/surftimer/SurfTimer/blob/5c4825b6161cbbda9f1455ec251b184f50e871f8/addons/sourcemod/scripting/surftimer/sql.sp#L6386

### Recommend statement

_RIGHT JOIN_ changed to _INNER JOIN_ to ensure the `mapname` column has matching values in both `ck_zones` and `ck_maptier`.

```sql
SELECT
    COUNT(DISTINCT `a`.`mapname`) + COUNT(1) AS `count`
FROM
    `ck_zones` `a`
INNER JOIN
    `ck_maptier` `b` ON
        `b`.`mapname` = `a`.`mapname`
WHERE
    `a`.`zonetype` = 3
    AND
    `a`.`zonegroup` = 0;
```

### Current statement query plan

|  id | select_type | table      | type  | possible_keys | key     | key_len | ref                 | rows | Extra                                        |
| --: | ----------- | ---------- | ----- | ------------- | ------- | ------- | ------------------- | ---- | -------------------------------------------- |
|   1 | PRIMARY     | <derived2> | ALL   | \N            | \N      | \N      | \N                  | 1270 |                                              |
|   2 | DERIVED     | b          | index | PRIMARY       | PRIMARY | 218     | \N                  | 254  | Using index; Using temporary; Using filesort |
|   2 | DERIVED     | a          | ref   | PRIMARY       | PRIMARY | 218     | surftimer.b.mapname | 5    | Using where                                  |

### Recommended statement query plan

|  id | select_type | table | type  | possible_keys | key     | key_len | ref                 | rows | Extra       |
| --: | ----------- | ----- | ----- | ------------- | ------- | ------- | ------------------- | ---- | ----------- |
|   1 | SIMPLE      | b     | index | PRIMARY       | PRIMARY | 218     | \N                  | 254  | Using index |
|   1 | SIMPLE      | a     | ref   | PRIMARY       | PRIMARY | 218     | surftimer.b.mapname | 5    | Using where |

## db_selectTotalBonusCount

https://github.com/surftimer/SurfTimer/blob/5c4825b6161cbbda9f1455ec251b184f50e871f8/addons/sourcemod/scripting/surftimer/sql.sp#L6359

### Recommended statement

Added additional _WHERE_ clause for `zonetype` returning only start bonus zones, reducing records processed for aggregation.

_RIGHT JOIN_ changed to _INNER JOIN_ to ensure the `mapname` column has matching values in both `ck_zones` and `ck_maptier`.

```sql
SELECT
    COUNT(DISTINCT `a`.`mapname`, `a`.`zonegroup`) AS `count`
FROM
    `ck_zones` `a`
INNER JOIN
    `ck_maptier` `b` ON
        `b`.`mapname` = `a`.`mapname`
WHERE
    `a`.`zonetype` = 1
    AND
    `a`.`zonegroup` > 0;
```

### Current statement query plan

|  id | select_type | table | type  | possible_keys | key     | key_len | ref                 | rows | Extra       |
| --: | ----------- | ----- | ----- | ------------- | ------- | ------- | ------------------- | ---- | ----------- |
|   1 | SIMPLE      | b     | index | PRIMARY       | PRIMARY | 218     | \N                  | 254  | Using index |
|   1 | SIMPLE      | a     | ref   | PRIMARY       | PRIMARY | 218     | surftimer.b.mapname | 5    | Using where |

### Recommended statement query plan

**The query plan for this statement is not altered.**

|  id | select_type | table | type  | possible_keys | key     | key_len | ref                 | rows | Extra       |
| --: | ----------- | ----- | ----- | ------------- | ------- | ------- | ------------------- | ---- | ----------- |
|   1 | SIMPLE      | b     | index | PRIMARY       | PRIMARY | 218     | \N                  | 254  | Using index |
|   1 | SIMPLE      | a     | ref   | PRIMARY       | PRIMARY | 218     | surftimer.b.mapname | 5    | Using where |

**Comment by RSCSurf** [comment]
Yeah, it would be better to use `JOIN` instead of `RIGHT JOIN`
