### ISSUE TITLE
[BUG] Bot not correctly replaying times on certains maps? 

### ISSUE THREAD

**Issue by breakthegreat** [surftimer/SurfTimer#52]
**Describe the bug**
Sometimes the bot won't load replay, stages replay especially for this map. It was working fine with z4lab 274 (at least with the !fixbot command) 

**Expected behavior**
Bot should replay the current record

**Screenshots**

![image](https://user-images.githubusercontent.com/64219376/80135293-05e4d100-856e-11ea-9229-5e3aba0ba665.png)

**Plugin List**

**Additional context**
Maybe a map issue? I'm 100% sure record replay files are here and as said before it was working fine with 274 z4lab. Tried !fixbot command at least 5 times same result. 
Any logs you guys wanna see?

**Comment by breakthegreat** [comment]
![image](https://user-images.githubusercontent.com/64219376/80135693-8d324480-856e-11ea-8f36-c1736cf51dfb.png)
POV of the bot.

**Comment by 13ace37** [comment]
ever tried setting the delay to 30?

**Comment by breakthegreat** [comment]
No, will try on next map and update here

**Comment by breakthegreat** [comment]
![image](https://user-images.githubusercontent.com/64219376/80144794-249e9400-857d-11ea-9c0f-4194e3b7459d.png)
Still some issue even with delay set up to 30.

**Comment by olokos** [comment]
@breakthegreat 
Is this still a thing with release 285?

**Comment by breakthegreat** [comment]
> @breakthegreat
> Is this still a thing with release 285?

I'll keep you updated for now no issue whatsoever

**Comment by FR33K1LL** [comment]
this happens to me as well on 285.95, sometimes !fb wont fix it the first time and i will have to use the cmd a couple times before it works.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by dPexxIAM** [comment]
this is most likely fixed with all the fixes and changes to replays, re-open else wise @breakthegreat
