### ISSUE TITLE
[BUG] Style times not being recorded if one already exists

### ISSUE THREAD

**Issue by Synert** [surftimer/SurfTimer#524]
If no time has been set, then everything works as expected. If a time is already set, everything else works as expected (replay bot updates, messages are printed, points given) but the time itself will not be saved. Observed while using 1.1.2-beta1 on servers SCEN and Thunderdome.

The bug appears to be caused by #501 and is fixed by undoing this change. This does cause [this Discord bug](https://github.com/surftimer/SurfTimer-discord/issues/21) to reappear, though.

**Comment by Bara** [comment]
Fixed in dev branch
