### ISSUE TITLE
[BUG] Unable to leave spectator mode

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer#564]
**Describe the bug**
If I join spectator on a player, then try to rejoin a team, it leaves me on spectate.  I used sm_r attempting to reset.  When that failed, I tried pressing M and joining a team.  The game reports that I joined T and/or CT, but leaves me spectating.  Only solution is to rejoin the server.

**Expected behavior**
Should just leave spectate mode.

**Comment by tslashd** [comment]
https://discord.com/channels/366959507764674560/379572504542445568/813067577693700146

**Comment by IG-PhantomX** [comment]
Haven't experienced this anomaly again, so closing.
