### ISSUE TITLE
[Suggestion] Create new bot replays if none exist

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer#568]
**Is your feature request related to a problem? Please describe.**
Coming from a very old ckSurf, I have some replay bots that are bugged on certain maps.  Deleting them is generally the best thing to do, but my issue is that on maps with 1k+ records, the odds of somebody getting a new record and setting a new bot is very low.

**Describe the solution you'd like**
It'd be nice to have a feature that IF no replay bot exists, then regardless of the run time, a new one is made.

**Comment by tslashd** [comment]
That should already be a thing.
ck_replace_faster_replays (or something along those lines), can you please confirm you have it set to 1?
Although it should not matter whether you have it as 1 cause there is no replay to replace so it should make a new one.
