### ISSUE TITLE
[Suggestion] Rank Title based only on normal mode

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer#573]
**Is your feature request related to a problem? Please describe.**
If a user switches the style they are surfing, their title changes with that style - so if they are #1 in low gravity, it shows they are the top #1 surfer on the server with that title.

**Describe the solution you'd like**
I would like to see the rank title displayed only reflecting the normal surf mode.

**Describe alternatives you've considered**
N/A

**Comment by tslashd** [comment]
I would recommend adding a new **ConVar** to determine the behavior of ranks as I can see server owners not wanting this feature, for example I would not want to force normal ranking on everyone, especially as there are angle surfers which do not really care about **Normal** ranks

**Comment by dPexxIAM** [comment]
I wouldn't consider this as an enhancement, the rank title will also show which style they are in E.G [SW-Rank]

**Comment by dPexxIAM** [comment]
After looking into this, I'm pretty certain you can remove the {style} strings from your skillgroups.cfg file to remove this functionality, let me know if this works.

**Comment by IG-PhantomX** [comment]
There are no {style} strings in my skillgroups.cfg.

Is there documentation about this and how to go about editing my skillgroup.cfg?

As it stands, the various styles are not showing up with a different tag; so it is insulting to our top Surfer that some bozo can also use the exact same title if they grind enough Low Gravity points, for example.

**Comment by dPexxIAM** [comment]
> There are no {style} strings in my skillgroups.cfg.
> 
> Is there documentation about this and how to go about editing my skillgroup.cfg?
> 
> As it stands, the various styles are not showing up with a different tag; so it is insulting to our top Surfer that some bozo can also use the exact same title if they grind enough Low Gravity points, for example.

https://github.com/surftimer/SurfTimer/blob/dev/addons/sourcemod/configs/surftimer/skillgroups.cfg

**Comment by seethingword** [comment]
Is there a way to make it to where it changes rank based on the type of style?
Like if someone is #1 in Normal style, their tag is #1 NM Surfer but if someone is #1 in FF, it shows #1 FF Surfer

**Comment by dPexxIAM** [comment]
> Is there a way to make it to where it changes rank based on the type of style? Like if someone is #1 in Normal style, their tag is #1 NM Surfer but if someone is #1 in FF, it shows #1 FF Surfer

Yes, if you check the skillgroups.cfg file I linked above, it includes a {style} prefix which you can use to achieve this.

@IG-PhantomX closing this issue since I feel it's irrelevant now

**Comment by seethingword** [comment]
How would one define the style? all it shows is the {style} parameter? do you put it in like {normal} , {lowgrav}, etc?
