### ISSUE TITLE
[Question] Is there a way to define the specific style in the skillgroups.cfg

### ISSUE THREAD

**Issue by seethingword** [surftimer/SurfTimer#575]
How would one define the style? all it shows is the {style} parameter inside the file? do you put it in like {normal} , {lowgrav}, etc?
Current:
	"1"
	{
		"rankTitle" "{orchid}#1 Surfer"
		"nameColour" "{darkred}"
		"rank" "1"
	}
	
suggested:
	"1"
	{
		"rankTitle" "{normal}{orchid}#1 NM Surfer"
		"nameColour" "{darkred}"
		"rank" "1"
	}
	"2"
	{
		"rankTitle" "{fastforward}{orchid}#1 FF Surfer"
		"nameColour" "{darkred}"
		"rank" "1"
	}
	
I'm wanting people to have different tags based on their rank in different styles

**Comment by dPexxIAM** [comment]
take a look at the skillgroups.cfg file in the repo, you don't need to define the style names yourself, just use {style}

**Comment by seethingword** [comment]
I dont want the same tags for different styles. i want to know if its possible to define different names for different style as shown above. I've tested it multiple different ways and 2 players still have the same tags
