### ISSUE TITLE
[BUG] Stuck in spectator mode

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer#585]
**Describe the bug**
Players are getting stuck in spectate mode, can't rejoin the team without reconnecting to the server.

**Expected behavior**
The player should be able to rejoin the team.

**Comment by nereyegeldikabi** [comment]
yea got same problrm after installing it

**Comment by tslashd** [comment]
Have you tried?
```
mp_respawn_on_death_ct 1
mp_respawn_on_death_t 1
```

**Comment by IG-PhantomX** [comment]
This did indeed fix it on that server.
