### ISSUE TITLE
[BUG] Prestrafe Breaks Randomly

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer#587]
**Describe the bug**
For random players, only semi-occasionally, they are unable to exceed the set zone speed limit for prestrafing.  So, if a start zone is set to 350 u/s, then the bugged user can only pre up to that limit.

**Expected behavior**
I expect a normal prestrafe of around 400-420 u/s (XY mode, of course).  

**Additional context**
Does not fix the bug:  Having players reload Steam and game client, force changing map on server.  Edit:  I just stayed through a server map change (through voting as opposed to admin force change), and now my pre is fixed.  Not sure if this fixes it every time, though.

Does fix the bug:  restart the server.

**Comment by dPexxIAM** [comment]
Commits were added to the dev branch recently which would solve this issue.

https://github.com/surftimer/SurfTimer/pull/579/commits/533006ba911865b7372c10d7d18946e16edcd682
https://github.com/surftimer/SurfTimer/pull/579/commits/f3f2d88932fb40456fa819eb2c51d7cd6b11841b
https://github.com/surftimer/SurfTimer/commit/bd094ef0c78d139de3ce9fc9bd244e27c82b1c29

**Comment by IG-PhantomX** [comment]
Thank you for the quick response on this.  I've implemented these changes and will close this ticket, if any other issues arise I'll re-open it.
