### ISSUE TITLE
[BUG] Checkpoints set player speed to 0, randomly occurring

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer#588]
**Describe the bug**
Occasionally, a player will get stopped at checkpoints which are by default set to 0 (unlimited) speed.  The bug occurs to a random player for the duration of a map.  Other players (99% of them) do not experience any issue with this zone setting.

**Expected behavior**
I expect all players to pass through the checkpoints unhindered.

**Additional context**
Not sure if this is related to the prestrafe bug I reported herehttps://github.com/surftimer/SurfTimer/issues/587 - I personally experienced that pre-bug on one map, then the next map I can pre but got stuck in the first checkpoint.

A cheap fix (albeit tacky fix) is changing checkpoint zone speeds to 10,000.

Edit:
Also not sure if related, but on this same map where I got set to 0 in checkpoints, I also cannot no-clip out of start/end zones.

**Comment by dPexxIAM** [comment]
Commits were added to the dev branch recently which would solve this issue.

https://github.com/surftimer/SurfTimer/pull/579/commits/533006ba911865b7372c10d7d18946e16edcd682
https://github.com/surftimer/SurfTimer/pull/579/commits/f3f2d88932fb40456fa819eb2c51d7cd6b11841b
https://github.com/surftimer/SurfTimer/commit/bd094ef0c78d139de3ce9fc9bd244e27c82b1c29

**Comment by IG-PhantomX** [comment]
Thank you for the quick response on this.  I've implemented these changes and will close this ticket, if any other issues arise I'll re-open it.
