### ISSUE TITLE
[BUG] !top is empty

### ISSUE THREAD

**Issue by skullboypl** [surftimer/SurfTimer#589]
**Describe the bug**
When map change !top is empty like threre are no record on MySql database but they are them and on !mrank i get info about myself. But top command not showing top lists just top list of current plays on map not all top list from this map played on server. So if you make record now it will show on list but after change map to the same map record is not longer seen on !top command

**Screenshots**
making some time: 
![image](https://github.com/surftimer/SurfTimer/assets/103207288/e612a03a-05ee-476e-98dd-1534222e3398)
then map change map to the same: 
![image](https://github.com/surftimer/SurfTimer/assets/103207288/16d3c9e9-ae78-4bf1-8e94-2195c6969abe)
no record found under !top command but on timer i can see my time

**Comment by justaFluffypanda** [comment]
Are there any associated SQL query errors in your sourcemod error log? Located in your .../csgo/addons/sourcemod/logs folder

**Comment by tslashd** [comment]
Have you tiered your maps? 
If not, that would most likely be the cause of your issue, otherwise please provide error logs like mentioned above

**Comment by skullboypl** [comment]
This happening on all maps even with name changed to _vxh or something Even i tryied new mySql database and still same issue. Before i use old ckSurf !top was working fine.

In logs no errors found even in mapname.log files No errors found 
But in mapnamelog there is somhere STEAMID: Skipping db_viewPersonalStageRecords (linear map) .

**Comment by skullboypl** [comment]
Server ip and port: 
146.59.52.224:27015

**Comment by skullboypl** [comment]
And if u have PB: time and after change map to same 
you have see PB on timer but when make worst time PB change to new worst one :

This is log from sever when i connect then finish map and new worst time change old better one And !top doesnt work before i make this map again 
"sv_pure value unchanged (current value is 0).

--------------------------------------------------------

Warning: Game server already logged into steam.  You need to use the sv_setsteamaccount command earlier.

Client "SpyArt" connected (xx.xx.xx.xxx:27005).

L 07/10/2023 - 20:22:26: [chat-processor.smx] Message formats generated for game 'csgo'.

L 07/10/2023 - 20:22:26: [chat-processor.smx] Successfully hooked a SayText2 chat hook.

[SourceComms++] Loading configs/sourcebans/sourcebans.cfg config file

[SourceComms++] Loading configs/sourcecomms.cfg config file

--------------------------------------------------------

sv_pure value unchanged (current value is 0).

--------------------------------------------------------

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_viewMapSettingsCallback in: 0.152343

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectMapZonesCallback in: 0.164062

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

*************************************

[TOKEN] TOKEN: xxxx

[TOKEN] TOKEN_API: xxx

*************************************

[TOKEN] Downloading Token ....

[TOKEN] IP: 146.59.52.224:27015

[TOKEN] TOKEN_API: xxxx

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_teleport with no model

Inserted trigger_teleport with no model

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_selectMapRecordCallback in: 0.058593

L 07/10/2023 - 20:22:27: [weapons.smx] Inactive players' data has been deleted

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_selectPlayerProCountCallback in: 0.046875

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectFastestBonusCallback in: 0.011718

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectBonusTotalCountCallback in: 0.011718

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectMapTierCallback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_selectRecordCheckpointsCallback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_db_CalcAvgRunTimeCallback in: 0.011718

xxx

[TOKEN] Token Status Is OK

*************************************

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_CountRankedPlayersCallback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_CountRankedPlayers2Callback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished db_selectSpawnLocationsCallback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_selectTotalBonusCountCallback in: 0.011718

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished sql_selectTotalStageCountCallback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished db_selectMapCurrentImprovementCallback in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_SelectAnnouncementsCallback in: 0.011718

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Normal in: 0.023437

L 07/10/2023 - 20:22:27: [SurfTimer] Finished loading server settings in 0.515625s

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Sideways in: 0.046875

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Half-Sideways in: 0.070312

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Backwards in: 0.082031

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Low-Gravity in: 0.105468

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Slow Motion in: 0.128906

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Fast Forward in: 0.152343

L 07/10/2023 - 20:22:27: [SurfTimer] : Finished SQL_selectReplayCPTicksCallback for Freestyle in: 0.164062

--------------------------------------------------------

sv_pure value unchanged (current value is 0).

--------------------------------------------------------

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

Setting CBaseEntity to non-brush model models/props/de_train/barrel.mdl

L 07/10/2023 - 20:22:36: [SurfTimer] Loading STEAM_1:0:114319873 - SpyArt settings

PutClientInServer: no info_player_start on level

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_teleport with no model

Inserted trigger_teleport with no model

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewPersonalRecords in 0.222656s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewPersonalBonusRecords in 0.035156s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Skipping db_viewPersonalStageRecords (linear map)

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewPersonalRecords in 0.023437s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewPlayerPoints in 0.023437s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_GetPlayerRank in 0.175781s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewPlayerOptions in 0.023437s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_CheckVIPAdmin in 0.023437s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewCustomTitles in 0.011718s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewCheckpoints in 0.023437s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_LoadCCP in 0.070312s

L 07/10/2023 - 20:22:36: [SurfTimer] STEAM_1:0:114319873: Finished db_viewPRinfo in 0.082031s

L 07/10/2023 - 20:22:36: [SurfTimer] Finished loading STEAM_1:0:114319873 - SpyArt settings in 0.621093s

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_multiple with no model

Inserted trigger_teleport with no model

Inserted trigger_teleport with no model

[SurfTimer] Transaction Sucessfully Done!

L 07/10/2023 - 20:23:46: [SurfTimer] : Finished SQL_db_CalcAvgRunTimeCallback in: 0.046875

L 07/10/2023 - 20:23:46: [SurfTimer] : Finished sql_CountRankedPlayersCallback in: 0.011718

L 07/10/2023 - 20:23:46: [SurfTimer] : Finished sql_CountRankedPlayers2Callback in: 0.023437

Dropped SpyArt from server: Disconnect
"

**Comment by skullboypl** [comment]
IN playerrank in mysql 0 data just one new run 
![image](https://github.com/surftimer/SurfTimer/assets/103207288/be9bf99b-789d-4bd4-ae86-5bc41708374c)

in player rekords: 
![image](https://github.com/surftimer/SurfTimer/assets/103207288/1b123d77-7a78-47c0-b627-6cdc8ddd9b2e)
 there just one 

In player times: 
![image](https://github.com/surftimer/SurfTimer/assets/103207288/d43303d4-97b6-4904-8b6c-da0b58d63e3b)

**Comment by tslashd** [comment]
> Have you tiered your maps?

I believe you have missed this from my previous reply. 
Please check your `ck_maptier` table, it needs to be populated in order for ranks to be saved.

**Comment by skullboypl** [comment]
![image](https://github.com/surftimer/SurfTimer/assets/103207288/658298cc-7c8e-4410-9aba-c63c668ad1f7)

**Comment by justaFluffypanda** [comment]
As suspected you haven't populated your ck_maptier table. 

[Save and then import this file into ck_maptier](https://raw.githubusercontent.com/surftimer/SurfTimer/dev/scripts/mysql-files/ck_maptier.sql)

**Comment by skullboypl** [comment]
Thx its working now.
