### ISSUE TITLE
Repeat bot 3 times on stages

### ISSUE THREAD

**Issue by kolya781** [surftimer/SurfTimer#607]
how to make the bot repeat on stages not 3 times, but only once?

**Comment by tslashd** [comment]
Change the `3` to `1` here:
https://github.com/surftimer/SurfTimer/blob/dev/addons/sourcemod/scripting/surftimer/replay.sp#L1323
and here:
https://github.com/surftimer/SurfTimer/blob/dev/addons/sourcemod/scripting/surftimer/replay.sp#L1330

**Comment by kolya781** [comment]
thanks and why is it that after compiling the plugin, the ban on start and stage jumping does not work for me more than 1 time?

**Comment by tslashd** [comment]
I do not know

**Comment by kolya781** [comment]
compiling on sourcemod 1.11. Sorry(

**Comment by tslashd** [comment]
No idea

**Comment by kolya781** [comment]
Thanks anyway
