### ISSUE TITLE
[Suggestion] Create zone to stop bonus time.

### ISSUE THREAD

**Issue by KristianP26** [surftimer/SurfTimer#65]
Create zone to stop bonus time.

**Comment by TheGunter24** [comment]
why would*t you simply make a "bonus end" ?

**Comment by sneak-it** [comment]
Does a regular 'Stop' zone not work?

**Comment by KristianP26** [comment]
@TheGunter24 there are maps where is teleport on bonus start to bonus end
@sneak-it nope

**Comment by sneak-it** [comment]
> @TheGunter24 there are maps where is teleport on bonus start to bonus end
> @sneak-it nope

That's silly, I would strip out the teleporter from the map in that case.

**Comment by 13ace37** [comment]
It's working! But with some weird workaround.
1. create a stop zone where you want to zone. 
1. change the `zonegroup` to the bonus number and the `zonename` to the name of the bonus.
1. done

**Comment by KristianP26** [comment]
Thanks @13ace37

**Comment by qawery-just-sad** [comment]
or create a cp zone for bonus

**Comment by KristianP26** [comment]
There are cp zones and stage zones for bonus you need to edit bonus and create new zone.

**Comment by dPexxIAM** [comment]
I would suggest doing as @sneak-it mentioned, however, a checker zone should suffice also i think!

**Comment by KristianP26** [comment]
@dPexxIAM I fixed it by TeletoStart zone but after this what @13ace37 writed i know how to fix it.

**Comment by dPexxIAM** [comment]
Cool, his fix is not ideal, though. It could be handled better by the timer itself!

**Comment by KristianP26** [comment]
@dPexxIAM Yes, you need edit zone in side of database and that is for someone hard.

**Comment by dPexxIAM** [comment]
There are other methods to do this currently. (checker zone)
