### ISSUE TITLE
[BUG] Names are saved sometimes in utf8 and sometimes in utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by KristianP26** [surftimer/SurfTimer#78]
Names are saved sometimes in utf8 and sometimes in utf8mb4_unicode_ci
![image](https://user-images.githubusercontent.com/28766334/80491124-981c1900-8962-11ea-90da-c7ce0ea5f3d9.png)

**Comment by PwnK** [comment]
https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L43

This could be a problem of us not using [`Database.SetCharset`](https://sm.alliedmods.net/new-api/dbi/Database/SetCharset) here because without that the charset can reset to default after connection problems.

**Comment by sneak-it** [comment]
This was done with commit 994df021c38ef29b336274f1558cf6ab7a9ea3f2 however was reverted with 2689c3502934ca8aa16f0c6c6b01393ddf1657ce because somehow people started getting crashes. I was not able to reproduce.

**Comment by olokos** [comment]
With 994df02 server completely crashes upon startup, without logs or anything.
Try it yourself @PwnK

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment]
I have looked through my entire ck_playertimes (10 250 entries) on my live servers and unable to find an instance of this.

Live servers using version 286. Unable to check with dev as this would mean running dev on live servers for several months to collect the information.
